### ISSUE TITLE
plz check attached img

### ISSUE THREAD

**Issue by jenty521** [rygo6/CardFramework-Unity#1] opened 2016-07-13 04:20 UTC
<img width="1920" alt="errer2" src="https://cloud.githubusercontent.com/assets/8857053/16791695/6dc2391e-48fc-11e6-8c96-db58e29c68e1.png">
<img width="1920" alt="errer1" src="https://cloud.githubusercontent.com/assets/8857053/16791708/8312a45c-48fc-11e6-8143-4342bee59848.png">

**Comment by rygo6** [comment] 2016-08-02 04:52
I cannot reproduce this. It appears like the images themselves are failing to import. Which has nothing to do with the code in the project.

**Comment by xianrei** [comment] 2016-12-02 16:48
pls check attached img

**Comment by Noqomo** [comment] 2016-12-06 06:52
@rygo6 if you look at your repo - the images aren't raster files - they are text files.

**Comment by FirasAwad** [comment] 2017-03-17 01:24
I'm having the same problem with the cards, I think there something wrong with files 
![screen shot 2017-03-16 at 6 21 46 pm](https://cloud.githubusercontent.com/assets/17697372/24025137/e7cabce6-0a75-11e7-9f20-322ced473677.png)

**Comment by FirasAwad** [comment] 2017-03-17 03:28
another screenshot
![screen shot 2017-03-16 at 8 27 00 pm](https://cloud.githubusercontent.com/assets/17697372/24027745/0ca87d12-0a87-11e7-9a91-09ebc34bc646.png)

**Comment by rygo6** [comment] 2017-04-14 07:05
You probably need to have git LFS installed. The images are stored on LFS.

**Comment by FirasAwad** [comment] 2017-04-15 00:10
I did run 
git lfs clone git@github.com:rygo6/CardExample-Unity.git 
Command and I got the following output

Cloning into 'CardExample-Unity'...
Warning: Permanently added the RSA host key for IP address '192.XX.XX.XXX' to the list of known hosts.
remote: Counting objects: 309, done.
remote: Total 309 (delta 0), reused 0 (delta 0), pack-reused 309
Receiving objects: 100% (309/309), 350.89 KiB | 455.00 KiB/s, done.
Resolving deltas: 100% (152/152), done.
Git LFS: (1 of 1 files, 55 skipped) 118.63 KB / 120.05 KB, 4.34 MB skipped     
[404] Object does not exist on the server
[a2969f550485523603443a7242a31f99c364e12fe6d46138b7f98b1d8d365eba] Object does not exist on the server
afterward, I tried to open the cards in Finder but still, I can't view them and in Unity 
the same error message after running the Assets --> Build All Bundles OSX

Could not create texture from Assets/CardFramework/AssetBundles/Cards/10_of_diamonds.png: File could not be read
UnityEditor.BuildPipeline:BuildAssetBundles(String, BuildAssetBundleOptions, BuildTarget)
AssetBundleBuild:BuildAllBundlesOSX() (at Assets/CardFramework/Editor/AssetBundleBuild.cs:11)


Am I still doing something wrong?

Thanks,

**Comment by migus88** [comment] 2017-04-16 18:49
Hi! I have lfs installed, but I still have a problem to clone the project. 
It won't clone and when I'm skipping the lfs, and then running 'git lfs pull', I'm getting the following error for every file (the hash is different of course):
[d950e4ed8c324494289352c2b9794d3e0129eb388b4ad5d43c2b95ae7abb8556] Object does not exist on the server: [404] Object does not exist on the server

**Comment by rygo6** [comment] 2017-05-05 03:29
I was reading around and discovered that github does not actually have git LFS enabled for public pulls. I had no idea. Github advertised LFS as 'transparent and seamless'. I am really disappointed to discover this.

I have deleted, reinitialized and force pushed the entire repo with git LFS removed. If you try to pull now it should get the images.

**Comment by FirasAwad** [comment] 2017-05-05 04:01
now I got this error 
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error(s) during clone:
git clone failed: exit status 128



but I did download it using the download button and it is working now, Thanks

**Comment by rygo6** [comment] 2017-05-07 23:30
That sounds like an error in your own github settings.

**Closed as completed** 2018-01-10 19:50 UTC
